services:
  app:
    image: junx27/event-app:v1.0.0
    container_name: event_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    entrypoint: ["go", "run", "main.go"]
    networks:
      - event_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          cpus: "0.5"

  database:
    image: postgres:15
    container_name: event_app_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - event_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres:

networks:
  event_network:
    driver: bridge
